name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd graphing_calculator; cargo build --verbose
    - name: Run tests
      run: cd graphing_calculator; cargo test --verbose
    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_COMPRESS: zip
        GHR_PATH: graphing_calculator/target/debug/
        GITHUB_TOKEN: ${{ secrets.token }}
